-- docs/db/schema-drift-objects.sql
-- B4 — снимок DDL «боевых объектов без DDL в репо» (интроспекция живой кассы
-- ygtphuxzazxdtyouxxir, снято 2026-07-13). Это НЕ полный pg_dump: только 8
-- объектов, перечисленных в CLAUDE.md → «Дрейф схемы». Реконструировано из
-- information_schema/pg_catalog (pg_get_functiondef / pg_get_viewdef / pg_indexes),
-- поэтому порядок опций и точные типы могут чуть отличаться от pg_dump — но
-- структура, дефолты, PK и индексы соответствуют проду.
--
-- Как пересникать (MCP execute_sql):
--   pg_get_viewdef('public.v_external_rates_latest'::regclass, true)
--   pg_get_functiondef('public.set_pair_margins(text,text,numeric,numeric,numeric)'::regprocedure)
--   pg_get_functiondef('public.replace_special_rates(jsonb)'::regprocedure)
--   information_schema.columns / pg_indexes для таблиц.
--
-- ⚠ Схему из репо развернуть нельзя (нет полного дампа). Источник истины —
--   живая БД. Этот файл — карта, чтобы не додумывать структуру.

-- ─────────────────────────────────────────────────────────────────────────────
-- external_rates — сырьё внешних котировок (Rapira, Tolunay, …). Одна строка на
-- (source, pair, fetched_at). v_external_rates_latest берёт последнюю по паре.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.external_rates (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- прод: nextval('external_rates_id_seq')
  source      text        NOT NULL,
  pair        text        NOT NULL,
  bid         numeric,
  ask         numeric,
  mid         numeric,
  raw         jsonb,
  fetched_at  timestamptz NOT NULL DEFAULT now(),
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS external_rates_fetched_at_idx ON public.external_rates USING btree (fetched_at DESC);
CREATE INDEX IF NOT EXISTS external_rates_source_pair_idx ON public.external_rates USING btree (source, pair, fetched_at DESC);

-- Последняя котировка на (source, pair).
CREATE OR REPLACE VIEW public.v_external_rates_latest AS
  SELECT DISTINCT ON (source, pair) source, pair, bid, ask, mid, fetched_at
    FROM public.external_rates
   ORDER BY source, pair, fetched_at DESC;

-- ─────────────────────────────────────────────────────────────────────────────
-- rapira_alert_state — референс-точка волатильности на пару (для алертов Rapira).
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.rapira_alert_state (
  pair        text        NOT NULL PRIMARY KEY,
  ref_mid     numeric,
  ref_at      timestamptz,
  updated_at  timestamptz NOT NULL DEFAULT now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- special_rates — СПЕЦ-КУРСЫ (НЕРЕЗ/СБП и т.п.). Полностью перезаписывается через
-- replace_special_rates(jsonb). kind/side/settle — категоризация; value — курс.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.special_rates (
  id            uuid        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  kind          text        NOT NULL,
  pair          text,
  side          text,
  settle        text,
  from_currency text,
  to_currency   text,
  value         numeric     NOT NULL,
  imported_at   timestamptz NOT NULL DEFAULT now(),
  updated_by    uuid
);

-- ─────────────────────────────────────────────────────────────────────────────
-- pairs — дрейф-КОЛОНКИ (сама таблица описана в store/rates.jsx; здесь только то,
-- чего нет в коде: маржинальная модель market_rate + buy/sell margin, is_master,
-- reverse_locked). rate = market_rate + buy_margin (см. set_pair_margins).
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.pairs ADD COLUMN IF NOT EXISTS market_rate    numeric;
ALTER TABLE public.pairs ADD COLUMN IF NOT EXISTS buy_margin     numeric NOT NULL DEFAULT 0;
ALTER TABLE public.pairs ADD COLUMN IF NOT EXISTS sell_margin    numeric NOT NULL DEFAULT 0;
ALTER TABLE public.pairs ADD COLUMN IF NOT EXISTS is_master      boolean NOT NULL DEFAULT false;
ALTER TABLE public.pairs ADD COLUMN IF NOT EXISTS reverse_locked boolean NOT NULL DEFAULT false;

-- Единая точка записи маржи в default-пару: rate = market + buy_margin.
CREATE OR REPLACE FUNCTION public.set_pair_margins(p_from text, p_to text, p_market numeric, p_buy_margin numeric, p_sell_margin numeric DEFAULT NULL::numeric)
 RETURNS void LANGUAGE plpgsql SET search_path TO 'public'
AS $function$
begin
  update public.pairs
     set market_rate = p_market,
         buy_margin  = p_buy_margin,
         sell_margin = coalesce(p_sell_margin, p_buy_margin),
         rate        = p_market + p_buy_margin,
         updated_at  = now()
   where from_currency = p_from and to_currency = p_to and is_default = true;
end $function$;

-- Полная замена special_rates (owner/admin only). Клиент шлёт массив строк.
CREATE OR REPLACE FUNCTION public.replace_special_rates(p_rows jsonb)
 RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
declare v_role text;
begin
  select role into v_role from public.users where id = auth.uid();
  if v_role not in ('owner','admin') then
    raise exception 'Only owner/admin can set special rates' using errcode = '42501';
  end if;

  delete from public.special_rates;

  insert into public.special_rates(kind, pair, side, settle, from_currency, to_currency, value, updated_by, imported_at)
  select coalesce(e->>'kind',''), e->>'pair', e->>'side', e->>'settle',
         e->>'from', e->>'to', (e->>'value')::numeric, auth.uid(), now()
  from jsonb_array_elements(coalesce(p_rows, '[]'::jsonb)) as e
  where (e->>'value') is not null;
end;
$function$;

-- ─────────────────────────────────────────────────────────────────────────────
-- offices.coinpoint_office_code — маппинг офиса кассы на офис сайта coinpoint (1:1).
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.offices ADD COLUMN IF NOT EXISTS coinpoint_office_code text;
